# Run on demand

```{r setup, include=FALSE, echo=FALSE}
library(dspatterns)
```

--> pointblank validation

- Ideal focus: single docs, presentations, book in Quarto
- Netlify continuous deployment (only works if Netlify knows how to build- hopefully Quarto gets this soon, otherwise only for Hugo sites for R users)
- GitHub actions to hurl site source files & render & deploy into production

## New Packages and Functions  

## This Chapter's Pattern

You want what you typically see to update online automatically based on any change you push. You care about keeping the link up to date with your local work.

## Explore

If you updating data and generating reporting on that changing data on an ad hoc basis, you'll probably want a simple system for pushing new data, generating an updated report, and ensuring that things didn't break and everything is still looking generally top notch.

When data changes (with updated records and/or with modified records) you'll be faced with a fair amount of uncertainty. And, since the data will have an impact on their reporting, we have to eliminate that source of uncertainty as much as possible.


## Understand

## Explain

## Share


