# Importing data for the first time


```{r setup, include=FALSE, echo=FALSE}
library(dspatterns)
```


Use: 

- readr and readxl
- janitor::clean_names() janitor::get_dupes()

Resources:

- https://garthtarr.github.io/meatR/janitor.html#excel_numeric_to_date()
- http://jenrichmond.rbind.io/post/digging-into-the-janitor-package/
- https://cran.r-project.org/doc/contrib/de_Jonge+van_der_Loo-Introduction_to_data_cleaning_with_R.pdf
- https://www.tandfonline.com/doi/pdf/10.1080/00031305.2017.1375989?needAccess=true

Goal: proactive resilient workflows for working with messy data (i.e., file organization, strategies, troubleshooting, talking to yourself / future collaborators, having difficult conversations about data and what you need)

pains:
- dates
- numbers becoming dates
- column names with spaces numbers or punctuation or other weird characters 
- missingness (i.e., blank cells or recoding missing values to NA)
- blank or extra misc rows/columns
- multiple header rows (https://alison.rbind.io/blog/2018-07-multiple-headers/)
- column types 
- factor levels
- duplicate values

## This chapter's pattern

- Explore: find out what went wrong? (diagnostic files, treasure hunt / glimpse / count / head / tail / readr::problems?? / janitor::get_dupes) [ this is a messy rmd file - leave behind in your dust when you are able to diagnose all the issues     - scratch file - save something tell them where ]
- Understand: is fix- solving the problem (stick to readxl / skip / col_types / NA / janitor::clean_names ) [ start a new clean rmd here for importing? ]
- Explain: make sure you can do this again (communication to yourself); never edit the raw file; Annotate the Rmd with WHATEVER, use a future child doc? all the text will be hidden but the code will run; maybe with something with pointblank to write checks for yourself?
- Share (Collaborate/Communicate): pointblank data dictionary as a conversation starter, documenting for others, writing the file out, advice for having conversations with data providers who ruin your life; rmd parent that uses the child?

## Explore

Getting new data can be really exciting but it can often result in a lot of work.
You have to import the data such that it's not a garbled mess, you have to understand how the data is organized, and, you may have to do some cleaning and data quality tasks.
The first few times you do this can be an exercise in frustration, involving much messing around until you feel you have a handle on things. That said, the goal of this chapter 
is to provide you with some workflows and many tips/tricks that'll serve you well when onboarding new datasets. 
We'll be working exclusively with tabular data for this chapter, using a variety of datasets of the messy variety to keep things real.

Let's be upfront about some of the challenging things you may have to deal with:

- getting dates in nonstandard formats
- having numbers transformed to dates (an Excel thing)
- seeing column names with spaces numbers or punctuation or other weird characters 
- taking stock of missingness (i.e., blank cells or recoding missing values to NA)
- blank or extra misc rows/columns
- multiple header rows (https://alison.rbind.io/blog/2018-07-multiple-headers/)
- identifying column types for import
- dealing with factor levels
- having duplicate values




## Understand


## Explain


## Share



