project:
  type: book
  output-dir: docs

book:
  twitter-card: true
  title: "A Data Science Pattern Language"
  author: "Alison Presmanes Hill and Richard Iannone"
  repo-actions:
    - source
  repo-url: "https://github.com/dspatterns/dspatterns-book"
  search: true
  # description: |
  #   A Data Science Pattern Language: Designing Projects with R will get you up
  #   and running with R. You'll learn many things in this book, with the
  #   main goals of enabling you to explore data, perform analysis on it, and
  #   communicate the results of that analysis. There are lots of little things
  #   to learn to get to that stage, but we'll take a structured approach using
  #   a collection of R packages.
  cover-image: cover.png
  page-navigation: true
  chapters:
    - index.qmd
    - "---"
    - part: "Onboarding patterns"
      chapters:
        - onboarding/patterns.qmd
        - onboarding/chapters.qmd
        - onboarding/book.qmd
        - onboarding/authors.qmd
        - onboarding/tools.qmd
    - "---"
    - primer-coding/01-hello-r.qmd
    - "---"
    - part: "Primer II: Quarto"
      chapters:
        - primer-quarto/01-hello-quarto.qmd
        - primer-quarto/02-source.qmd
        - primer-quarto/03-coding.qmd
        - primer-quarto/04-rendering.qmd
        - primer-quarto/05-writing.qmd
        - primer-quarto/06-how-it-works.qmd
        - primer-quarto/07-chunks.qmd
        - primer-quarto/08-figures.qmd
        - primer-quarto/09-tables.qmd
        - primer-quarto/10-options.qmd
        - primer-quarto/11-formats.qmd
    - "---"
    - part: "Part 1: MVPs"
      chapters:
        - p01-mvp/01-dataframes.qmd
        - p01-mvp/02-data-wrangling.qmd
        - p01-mvp/03-data-viz.qmd
    - "---"
    - part: "Part 2: Workflow patterns"
      chapters:
        - p02-workflow/01-projects.qmd
        - p02-workflow/02-github.qmd
    - "---"
    - part: "Part 3: Local data patterns"
      chapters:
        - p03-import/01-import-data-first-time.qmd
        - p03-import/02-import-data-next-time.qmd
        - p03-import/03-import-data-formats.qmd
    - "---"
    - part: "Part 4: Aggregation patterns"
      chapters:
        - p04-aggregate/01-careful-counting.qmd
        - p04-aggregate/02-rolling-up-data.qmd
        - p04-aggregate/03-slicing-and-dicing-data.qmd
        - p04-aggregate/04-making-datasets-longer.qmd
        - p04-aggregate/05-windows-of-data.qmd
        - p04-aggregate/06-making-datasets-wider.qmd
        - p04-aggregate/07-project-1.qmd
    - "---"
    - part: "Part 5: Batch mode"
      chapters:
        - p05-batch/01-batch-style.qmd
        - p05-batch/02-batch-create.qmd
        - p05-batch/03-parameters.qmd
        - p05-batch/04-style-package.qmd
        - p05-batch/05-project-2.qmd
    - "---"
    - part: "Part 6: Production mode"
      chapters:
        - p06-production/01-run-on-demand.qmd
        - p06-production/02-run-on-schedule.qmd
        - p06-production/03-run-on-conditions.qmd
        - p06-production/04-project-3.qmd
    - "---"
  appendices:
    - appendix/85-tidying-data-for-analysis.qmd
    - appendix/87-transformations-dates-times.qmd
    - appendix/88-closer-look-r-programming.qmd
    - appendix/89-string-transformations.qmd
    - appendix/90-lists-and-factors.qmd
    - appendix/91-more-ggplot-1.qmd
    - appendix/92-more-ggplot-2.qmd
    - appendix/93-making-presentation-tables.qmd

format:
  html:
    theme:
      - cosmo
      - style/style.scss
      - style/fonts.scss
    toc: true
    toc-depth: 2
    cover-image: cover.png
    code-link: true
    code-annotations: below
    callout-appearance: simple

execute:
  collapse: false

bibliography: references.bib
