project:
  type: book
  output-dir: docs

book:
  twitter-card: true
  title: "A Data Science Pattern Language"
  author: "Richard Iannone and Alison Presmanes Hill"
  repo-actions:
    - source
  repo-url: "https://github.com/dspatterns/dspatterns-book"
  sidebar:
    style: docked
    background: light
  bread-crumbs: false
  search: true
  # description: |
  #   A Data Science Pattern Language: Designing Projects with R will get you up
  #   and running with R. You'll learn many things in this book, with the
  #   main goals of enabling you to explore data, perform analysis on it, and
  #   communicate the results of that analysis. There are lots of little things
  #   to learn to get to that stage, but we'll take a structured approach using
  #   a collection of R packages.
  cover-image: cover.png
  chapters:
    - index.qmd
    - "---"
    - part: "Onboarding Patterns"
      chapters:
        - m-onboarding/01-patterns.qmd
        - m-onboarding/02-chapter-pattern.qmd
        - m-onboarding/03-about-book.qmd
        - m-onboarding/04-about-authors.qmd
        - m-onboarding/05-prerequisites.qmd
    - "---"
    - n-primer-coding/01-quick-start.qmd
    - "---"
    - o-primer-quarto/01-hello-quarto.qmd
    - "---"
    - part: "Part 1: MVPs"
      chapters:
        - p01-mvp/01-dataframes.qmd
        - p01-mvp/02-data-wrangling.qmd
        - p01-mvp/03-data-viz.qmd
    - "---"
    - part: "Part 2: Data Management Patterns"
      chapters:
        - p02-data/01-projects.qmd
        - p02-data/02-import-data-first-time.qmd
        - p02-data/03-import-data-next-time.qmd
        - p02-data/04-import-data-formats.qmd
    - "---"
    - part: "Part 3: Aggregation Patterns"
      chapters:
        - p03-aggregate/01-careful-counting.qmd
        - p03-aggregate/02-rolling-up-data.qmd
        - p03-aggregate/03-making-datasets-longer.qmd
        - p03-aggregate/04-making-datasets-wider.qmd
    - "---"
    - part: "Part 4: Batch Patterns"
      chapters:
        - p04-batch/01-batch-plots.qmd
        - p04-batch/02-batch-tables.qmd
    - "---"
  appendices:
    - q-appendix/01-tidying-data-for-analysis.qmd
    - q-appendix/02-transformations-dates-times.qmd
    - q-appendix/03-closer-look-r-programming.qmd
    - q-appendix/04-string-transformations.qmd
    - q-appendix/05-lists-and-factors.qmd
    - q-appendix/06-more-ggplot-1.qmd
    - q-appendix/07-more-ggplot-2.qmd
    - q-appendix/08-making-presentation-tables.qmd

format:
  html:
    theme:
      - cosmo
      - style/style.scss
      - style/fonts.scss
    toc: true
    toc-depth: 2
    cover-image: cover.png
    code-link: true
    code-line-numbers: false
    code-annotations: below

execute:
  collapse: true

bibliography: references.bib
