project:
  type: book
  output-dir: docs

book:
  title: "A Data Science Pattern Language"
  author: "Alison Presmanes Hill and Richard Iannone"
  repo-actions:
    - source
  repo-url: "https://github.com/dspatterns/dspatterns-book"
  sidebar:
    style: docked
    background: light
  search: true
  description: |
    A Data Science Pattern Language: Designing Projects with R* will get you up
    and running with R. You'll learn many things in this book, with the
    main goals of enabling you to explore data, perform analysis on it, and
    communicate the results of that analysis. There are lots of little things
    to learn to get to that stage, but we'll take a structured approach using
    a collection of R packages.
  cover-image: cover.png
  chapters:
    - index.qmd
    - prereqs.qmd
    - part: "Part 1: Quarto"
      chapters:
        - 01-source.qmd
        - 02-coding.qmd
        - 03-rendering.qmd
        - 04-writing.qmd
        - 05-how-it-works.qmd
        - 06-chunks.qmd
        - 07-figures.qmd
        - 08-tables.qmd
        - 09-options.qmd
        - 10-formats.qmd
    - part: "Part 2: Starting out"
      chapters:
        - 11-intro.qmd
        - 12-starting-with-projects.qmd
        - 13-starting-with-github.qmd
        - 14-importing-data-first-time.qmd
        - 15-importing-data-next-time.qmd
    - part: "Part 3: Getting into it"
      chapters:
        - 16-careful-counting-patterns.qmd
        - 17-rolling-up-data.qmd
        - 18-slicing-and-dicing-data.qmd
        - 19-making-datasets-longer.qmd
        - 20-windows-of-data.qmd
        - 21-making-datasets-wider.qmd
        - 22-project-1.qmd
    - part: "Part 4: Batch mode"
      chapters:
        - 23-batch-style.qmd
        - 24-batch-create.qmd
        - 25-parameters.qmd
        - 26-style-package.qmd
        - 27-project-2.qmd
    - part: "Part 5: Production mode"
      chapters:
        - 28-run-on-demand.qmd
        - 29-run-on-schedule.qmd
        - 30-run-on-conditions.qmd
        - 31-project-3.qmd
  appendices:
    - 81-installing-r.qmd
    - 82-starting-with-r.qmd
    - 83-data-transformation-dplyr.qmd
    - 84-data-visualization-ggplot.qmd
    - 85-tidying-data-for-analysis.qmd
    - 86-importing-data-common-formats.qmd
    - 87-transformations-dates-times.qmd
    - 88-closer-look-r-programming.qmd
    - 89-string-transformations.qmd
    - 90-lists-and-factors.qmd
    - 91-more-ggplot-1.qmd
    - 92-more-ggplot-2.qmd
    - 93-making-presentation-tables.qmd

format:
  html:
    theme:
      - cosmo
      - style/style.scss
      - style/fonts.scss
    toc: true
    toc-depth: 2
    cover-image: cover.png
    code-link: true
