# Writing

```{r setup, include=FALSE, echo=FALSE}
library(dspatterns)
```


Everything that is not code in your `.Rmd` is called narrative text, and can be styled with Markdown. Markdown is a plain text formatting syntax, which means everything you see in the file itself can be typed with a normal keyboard. Below is an example:


## Add structure

You can use Markdown to organize your `.Rmd` file with headings. Headings are useful for organizing your document into sections, and with Markdown formatting you can have up to 6 types/sizes of headers. Use a hash symbol like `#` before the label to create a new header.

drop-down IDE navigator

outline pane

## Add formatting

All narrative text in your `.Rmd` file can be formatted to add **bold**, *italics*, bulletted lists, numbered lists, superscripts<sup>1</sup>, and subscripts<sub>1</sub>.

## Insert elements

do side by side here

<https://rstudio.github.io/visual-markdown-editing/#/>

here add a bibliography, a static image, equation,

<https://rmd4medicine.netlify.app/book/_book/add-text-with-markdown.html>

this is markdown

## What is Markdown?

-   Markdown is a particular type of markup language.

-   Markup languages are designed produce documents from plain text.

## Visual Markdown Editor

emoji, spell checking, commenting
