# About the Authors {-}

:::{.alison}

Alison started learning to code in R right after grad school. The cost of an SAS license was the initial nudge toward R life. Alison found that R was a joy to learn! Also, she found it much easier (and more fun) to teach than SAS. During her professorship at OHSU, Alison developed and taught a popular statistics course. The initial goal was to improve the learning experience of stats at the department. The combination of stats and data visualization was a pairing that students loved. Even those that weren’t enrolled in the course were sitting in on the lectures. Given all that, goal achieved!

Alison taught people within different organizations when part of the RStudio Education Team. She developed dozens of workshops and educational materials. This got the R community excited about using R for things aside from stats. Now at Voltron Data, Alison is now able to combine her teaching and product planning skills. Her focus there is creating engaging online experiences for community learning.

:::

:::{.rich}

Rich looked at R briefly in 2010 and waited *two years* to start using it. But once he did, he really liked it! It was around 2013 when he got bitten by the package-development bug and, since then, he's been on a tear when it comes to making useful packages for R users. Rich was blown away by the wealth of great packages available and was then inspired to make his own unique contributions. He aimed toward making really useful packages and, after some false starts, Rich never really gave up on his R dreams. Given all that, goal achieved!

Rich enjoys interacting with people from different organizations and showing them what could be done in R. He's given a ton o' talks and a good number of workshops as well. Now at Posit PBC, Rich has combined his package development work with all sorts of outreach activities. He focuses a lot on helping people use R tools to do work better and faster.

:::
