project:
  type: book
  output-dir: docs

book:
  title: "A Data Science Pattern Language"
  author: "Alison Presmanes Hill and Richard Iannone"
  sidebar:
    style: docked
    background: light
  search: true
  description: |
    A Data Science Pattern Language: Designing Projects with R* will get you up
    and running with R. You'll learn many things in this book, with the
    main goals of enabling you to explore data, perform analysis on it, and
    communicate the results of that analysis. There are lots of little things
    to learn to get to that stage, but we'll take a structured approach using
    a collection of R packages.
  cover-image: cover.png
  chapters:
    - index.Rmd
    - part: "Part 1"
      chapters:
        # "Section 1"
        - 01-starting-with-r.Rmd
        - 02-importing-raw-and-messy-data.Rmd
        # "Section 2"
        - 03-careful-counting-patterns.Rmd
        - 04-rolling-up-data.Rmd
        - 05-slicing-and-dicing-data.Rmd
        - 06-making-datasets-longer.Rmd
        - 07-windows-of-data.Rmd
        - 08-making-datasets-wider.Rmd # NOTES: transforming data for tables and modeling applications
        - 09-project-1.Rmd,
    - part: "Part 2"
      chapters:
        # "Section 3"
        - 10-transformations-dates-times.Rmd # NOTE: use the {clock} package
        - 11-ordering-data-to-make-better-plots.Rmd # Uses factors
        - 12-more-plotting-with-ggplot-i.Rmd
        - 13-more-plotting-with-ggplot-ii.Rmd
        - 14-project-2.Rmd
        # "Section 4"
        - 15-a-closer-look-at-r-programming.Rmd
        - 16-string-transformations.Rmd # str_detect, str_replace, word()
        - 17-r-lists.Rmd
        - 18-project-3.Rmd
        # "Appendix"
        - appendix.Rmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    cover-image: cover.png
    code-link: true
