on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # run every day at 11 PM
    - cron: '0 23 * * *'

name: build-book

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Install R packages
        run: |
         install.packages("remotes")
         install.packages("tidyverse")
         install.packages("quarto")
         install.packages("palmerpenguins")
         install.packages("gt")
         install.packages("DT")
         install.packages("ggridges")
         install.packages("skimr")
         remotes::install_github("dspatterns/dspatterns")
         remotes::install_github("apreshill/bakeoff")
        shell: Rscript {0}

      - name: "Install Quarto and render project"
        uses: pommevilla/quarto-render@v0.3.5

      - name: Deploy to Netlify
        if: contains(env.isExtPR, 'false')
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: 'docs'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
          # these all default to 'true'
          enable-pull-request-comment: false
          enable-commit-comment: false
          # enable-commit-status: true
          # overwrites-pull-request-comment: true
        timeout-minutes: 1
